panel/urls.py
from django.conf.urls import url

from .views import *

app_name = 'userprofile'
urlpatterns = [
	url(r'^$', index, name='index'),


	url(r'^user/list/$', user_list, name='user-list'),
	url(r'^user/list/removed/$', user_list_removed, name='user-list-removed'),
	url(r'^user/create/', user_create, name='user-create'),
	url(r'^user/edit/(?P<id>[0-9]+)/', user_edit, name='user-edit'),
	url(r'^user/remove/(?P<id>[0-9]+)/', user_remove, name='user-remove'),

	url(r'^section/list/$', section_list, name='section-list'),
	url(r'^section/create/', section_create, name='section-create'),
	url(r'^section/edit/(?P<id>[0-9]+)/', section_edit, name='section-edit'),
	url(r'^section/remove/(?P<id>[0-9]+)/', section_remove, name='section-remove'),

	url(r'^userrule/list/$', userrule_list, name='userrule-list'),
	url(r'^userrule/create/', userrule_create, name='userrule-create'),
	url(r'^userrule/edit/(?P<id>[0-9]+)/', userrule_edit, name='userrule-edit'),
	url(r'^userrule/remove/(?P<id>[0-9]+)/', userrule_remove, name='userrule-remove'),


	url(r'^workday/list/$', workday_list, name='workday-list'),
	url(r'^workday/create/', workday_create, name='workday-create'),
	url(r'^workday/edit/(?P<id>[0-9]+)/', workday_edit, name='workday-edit'),
	url(r'^workday/remove/(?P<id>[0-9]+)/', workday_remove, name='workday-remove'),



	url(r'^task/list/$', task_list, name='task-list'),
	url(r'^task/create/', task_create, name='task-create'),
	url(r'^task/edit/(?P<id>[0-9]+)/', task_edit, name='task-edit'),
	url(r'^task/remove/(?P<id>[0-9]+)/', task_remove, name='task-remove'),



	url(r'^test/$', test, name='test'),
	url(r'^main/settings/$', main_settings, name='main-settings'),

	url(r'^user/list/$', user_list, name='user-list'),
	url(r'^daily-check/list/$', daily_check_list, name='daily-check-list'),
	# path('start', StartView.as_command_view()),
	# path('author', AuthorCommandView.as_command_view()),
	# path('author_inverse', AuthorInverseListView.as_command_view()),
	# path('author_query', login_required(AuthorCommandQueryView.as_command_view())),
	# path(UnknownView.as_command_view()),
	# path(r'author_(?P<name>\w+)', AuthorName.as_command_view()),


]

general/models.py
from django.db import models

# Create your models here.

panel/models.py
from django.conf import settings
from django.db import models
from django.db.models import signals
from django.utils.translation import ugettext as _

# Create your models here.
from general.functions import path_and_rename
from panel.utils import utils
from panel.tasks import send_task_finished_info, send_task_canceled_info, send_task_created_info


class Section(models.Model):
    title = models.CharField(max_length=255)
    director = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name='director')
    short_text = models.CharField(max_length=500,blank=True,null=True)
    deleted = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title



class RuleUserModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    userrule = models.ForeignKey("UserRule",on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = ['user', 'userrule']

class WorkDay(models.Model):
    title = models.CharField(max_length=255)
    day = utils.IntegerRangeField(min_value=1, max_value=7,unique=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class WorkDayUser(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    work_day = models.ForeignKey("WorkDay",on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        unique_together = ['user', 'work_day']

class DailyCheck(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True)
    is_verified = models.BooleanField(default=False)
    date_day = models.DateField()
    date = models.DateTimeField()
    class Meta:
        unique_together = ['date_day', 'user']

class EmployeeTask(models.Model):
    title = models.CharField(max_length=255)
    section = models.ForeignKey('Section',blank=True,null=True,related_name='section_for')
    author = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name='author_for')
    employee = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True,null=True,related_name='employee_for')
    content = models.TextField(max_length=500,blank=True,null=True)
    is_finished = models.BooleanField(default=False)
    is_canceled = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

def employee_task_item_remove(sender, instance, *args, **kwargs):
    send_task_canceled_info(instance.id,)
def employee_task_item_save(sender, instance, created, *args, **kwargs):
    print('')
    # if instance.is_finished:
    #     send_task_finished_info(instance.id,)
    if instance.is_canceled:
        send_task_canceled_info(instance.id,)
    if created:
        send_task_created_info(instance.id,)
signals.post_save.connect(employee_task_item_save, sender=EmployeeTask)
signals.pre_delete.connect(employee_task_item_remove, sender=EmployeeTask)



UserRuleSTCHOICE  = (
    ('date',_('Date')),
    ('title',_('Title')),
    ('code',_('Code')),
    ('short_text',_('Short text')),
)

WorkdayCHOICE = (
    ('date',_('Date')),
    ('day',_('day')),
    ('title',_('Title')),
)
UserRuleCodeCHOICE = (
    ('dashboard',_('Dashboard')),
    ('main-settings',_('Main settings')),

    ('user-list',_('User list')),
    ('user-create',_('User create')),
    ('user-edit',_('User edit')),

    ('section-list',_('Section list')),
    ('section-create',_('Section create')),
    ('section-edit',_('Section edit')),
    ('section-remove',_('Section remove')),

    ('workday-list',_('Workday list')),
    ('workday-create',_('Workday create')),
    ('workday-edit',_('Workday edit')),
    ('workday-remove',_('Workday remove')),

    ('task-list',_('Task list')),
    ('task-create',_('Task create')),
    ('task-edit',_('Task edit')),
    ('task-remove',_('Task remove')),
)

class UserRule(models.Model):
    title = models.CharField(max_length=255)
    code = models.CharField(choices=UserRuleCodeCHOICE,max_length=50,unique=True)
    short_text = models.CharField(max_length=500,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

class MainSettings(models.Model):
    title = models.CharField(max_length=255)
    delay_days = models.IntegerField(default=0)
    big_logo = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    small_logo = models.ImageField(upload_to=path_and_rename, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title

general/views.py
import datetime

from django.conf import settings
from django.shortcuts import render

# Create your views here.
from panel.models import MainSettings


def base(req=None):

    data = {
        'now':datetime.datetime.now(),
        'base_site_name' : settings.SITE_NAME,
        'non_operate' : ['waiting','paided','ordered','closed','saled'],
        'base_main_settings':MainSettings.objects.filter().order_by('-date').first(),
        # 'base_categories':Menu.objects.filter(status=True,menu_type='dynamic-menu').filter(parent=None).order_by('order_index'),
    }
    return data

def base_auth(req=None):

    data = {
        'now':datetime.datetime.now(),
        'base_site_name' : settings.SITE_NAME,
        # 'base_categories':Menu.objects.filter(status=True,menu_type='dynamic-menu').filter(parent=None).order_by('order_index'),
        'base_profile' : req.user,
        'base_main_settings':MainSettings.objects.filter().order_by('-date').first(),
        'non_operate' : ['waiting','paided','ordered','closed','saled'],
    }
    return data

templates/panel/general/daily-check/section-form.html
{% extends 'base-main.html' %}
{% load static %}
{% load i18n %}

{% block css_block %}

  <link rel="stylesheet" href="{% static 'local/vendors/jsgrid/jsgrid.min.css' %}">
  <link rel="stylesheet" href="{% static 'local/vendors/jsgrid/jsgrid-theme.min.css' %}">
  <style>
        #js-grid{
            height: 500px;
            width: 100%;

        }
  </style>
{% endblock %}
{% block content_block %}
        <div class="content-wrapper">
          <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">{% trans 'Section' %}</h4>
                    {% if data_obj %}
                    <p class="card-description">
                        {{ data_obj.title }}
                    </p>
                    {% endif %}
                  <form class="forms-sample" method="post" action="">
                      {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">{% trans 'Title' %}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_director">{% trans 'Director' %}</label>
                        {{ form.director }}
                    </div>
                    <div class="form-group">
                        <label for="id_short_text">{% trans 'Short text' %}</label>
                        {{ form.short_text }}
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">{% trans 'Submit' %}</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    <!-- content-wrapper ends -->
    {% endblock %}
  {% block js_block %}

    <script>
        activeMenu('ui-sections');
    </script>

<script src="{% static 'local/vendors/sweetalert/sweetalert.min.js' %}"></script>
<script src="{% static 'local/vendors/jquery.avgrund/jquery.avgrund.min.js' %}"></script>
<script>
    {% if messages %}
        {% for message in messages %}
          swal({
            title: '{% trans 'Congratulations' %}!',
            icon: 'success',
            text: '{{ message }}',
            button: {
              text: "{% trans 'OK' %}",
              value: true,
              visible: true,
              className: "btn btn-primary"
            }
          });
        {% endfor %}
    {% endif %}
</script>
  {% endblock %}

templates/panel/general/daily-check/section-list.html
{% extends 'base-main.html' %}
{% load static %}
{% load i18n %}

{% block css_block %}
<style>
    .main-data-content-div { overflow: auto; height: 500px; }
    .main-data-content-div thead th { position: sticky; top: 0; }

    /* Just common table stuff. Really. */
    .main-data-content-div table  { border-collapse: collapse; width: 100%; }
    {# #main-data-content th, td { padding: 8px 16px; } #}
    .main-data-content-div th     { background:#eee; }
</style>
{% endblock %}
{% block content_block %}
    <div class="content-wrapper">
      <div class="row  grid-margin">


        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <form class="" id="main-search-form" method="post">
                  {% csrf_token %}
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <div class="col-sm-12">
                            {{ search_form.search }}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <div class="form-group row">
                          <div class="col-sm-12">
                            {{ search_form.field_list }}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-1">
                        <div class="form-group row">
                          <div class="col-sm-12">
                            {{ search_form.order_type }}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-3">
                        <div class="form-group row">
                          <div class="col-sm-12">
                            <button type="button" onclick="searchForm()" class="btn btn-primary mb-2">{% trans 'Search' %}</button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <input type="hidden" name="page-num" id="page-num" value="1"/>
              </form>
            </div>
          </div>
        </div>


        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">{% trans 'Section list' %}</h3>

              <div id="js-grid-sortable " class="jsgrid main-data-content-div" style="position: relative; height: 500px; width: 100%;" >

              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
    <!-- content-wrapper ends -->
    {% endblock %}
  {% block js_block %}
    <script>
        var search_form = $('#main-search-form');
        var main_data_content = $('.main-data-content-div');
        $( document ).ready(function() {
            searchForm();
        });
          search_form.submit( function(eventObj) {
              searchForm();
              eventObj.preventDefault();

          });
        function searchForm() {
            $('#page-num').val(1);
            main_data_content.html('<div style="width: 100%;text-align:center;"><img src="{% static 'local/images/pageloader.gif' %}"></div>');
          $.post('',search_form.serialize())
              .done(function (result) {
                  main_data_content.html(result['main_result']);
                  {#document.getElementById('customer-count-div').innerHTML = '<span>'+result['customer_count']+'</span>';#}
                  $('#page-num').val(2);
            }).fail(function () {
                  main_data_content.html('');
          });
        }
    </script>




    <script>
        var is_active = true;
        var has_data = true;
            $('.main-data-content-div').on('scroll', function() {
                console.log("-------------------------------------------------------------------------------");
                if ($(this).scrollTop() +
                    $(this).height()>=
                    ($(this).height() + 250) && is_active && has_data) {
                    infinityForm();
                    // alert('End of DIV is reached!');
                }
            });


        function infinityForm() {
            is_active = false;
              $.post('',search_form.serialize())
                  .done(function (result) {
                      $('.main-data-content-div tbody').append(result['main_result']);
                      if(result['main_result'] != ''){
                          $('#page-num').val(parseInt($('#page-num').val()) + 1);
                      }else{
                          has_data = false;
                      }
                      is_active = true;

                      console.log(result)
                }).fail(function () {
                    is_active = true;
              });
         }
    </script>
    <script>
        activeMenu('ui-sections');
    </script>

<script>

        const swalWithBootstrapButtons = Swal.mixin({
          customClass: {
            confirmButton: 'btn btn-success',
            cancelButton: 'btn btn-danger'
          },
          buttonsStyling: false
        });

        function deleteDataItem($url, $id) {

            swalWithBootstrapButtons.fire({
            title: 'Sure?',
            text: "Are you sure?",
              type: 'warning',
              showCancelButton: true,
              confirmButtonText: 'Yes!',
              cancelButtonText: 'No!',
              reverseButtons: true
            }).then((result) => {
              if (result.value) {
                    $.post($url,{'csrfmiddlewaretoken': '{{ csrf_token }}'})
                        .done(function (result) {
                            if (result['message_code']){
                                $('#list-item-'+$id).remove();
                            }
                        });
              } else if (
                /* Read more about handling dismissals below */
                result.dismiss === Swal.DismissReason.cancel
              ) {
                swalWithBootstrapButtons.fire(
                    'Cancelled',
                    'You are cancelled!',
                    'error'
                )
              }
            });
        }
</script>

  {% endblock %}